// Navigation
export const NAVIGATE_TO_PAGE = 'NAVIGATE_TO_PAGE'

// Entities
// Pokemon
export const SELECT_POKEMON = 'SELECT_POKEMON'
export const UPDATE_POKEMON_LOCATION = 'UPDATE_POKEMON_LOCATION'
export const GET_ALL_POKEMON = 'GET_ALL_POKEMON'